### ISSUE TITLE
svn revert problem

### ISSUE THREAD

**Issue by oOBlinkOo** [ki82/svn-revert-plugin#2]
hi im testing jenkins with  svn revert.
i can't revert the commit.
if i add a new file : Will not revert since some changes in commit(s) outside workspace detected.
if i delete: Will not revert since some changes in commit(s) outside workspace detected.
if i update any file:  Will not revert since some changes in commit(s) outside workspace detected.
if i just rebuild  but no add , update , delete files in the folder: Will not revert since there are no changes in current build.
i always build in this order success , inestable.
im making a project to build instable to test.
here are the result :
Build step 'Jenkins Text Finder' changed build result to UNSTABLE
Will not revert since some changes in commit(s) outside workspace detected.
Finished: UNSTABLE

and i don't know what im doing wrong.

**Comment by davidparsson** [comment]
Is the Jenkins job configured to check out the part of the source tree that's being modified by the commit? This message is displayed when one or more files in the commit is _not_ in the source tree being checked out by Jenkins.

For example, this message will be shown if Jenkins only checks out

```
folder1/
  file1.txt
```

but the commit modifies both `file1.txt` and `file2.txt` in the structure below

```
folder1/
  file1.txt
folder/2
  file2.txt
```

**Comment by oOBlinkOo** [comment]
in the last test i modified one file is not in the src folder you are right in this case.
but in the others?
i have this structure in my svn:
folder1
     src
    webcontent
   setting
     ....

in my jenkins i read all the folder. 
how i said before if i add a new file it detect, if i modified, delete the svn show me the first message in my first comment. 
supposedly the plugin can revert if i add , modified or delete something only if the build is unstable?

**Comment by davidparsson** [comment]
Since your directory structure isn't indented, it's not entirely easy to tell what you mean, but I'm assuming Jenkins checks out the entire source tree. Right?

The plugin will try to revert only if all of these conditions are met:
- the previous build is stable (green)
- the previous build is completed
- the current build is unstable
- the current build contains changes – a new commit not in the previous build
- all changes in the commit are in the workspace

The plugin should be able to handle both added, deleted and modified files. Are those conditions met in your case?

**Comment by oOBlinkOo** [comment]
yes my jenkins check out all the the files in the folder.

see this test.
im goint to build successful the console output is:
im testing just 1 folder : (services) this is my  workspace

Started by user oOBlinkOo
Building in workspace /var/lib/jenkins/jobs/folder/workspace
Updating https://subversion.assembla.com/svn/x/trunk/Aplication/folder/src/com/ws/ios/services at revision '2015-02-24T18:35:29.135 -0500'
At revision 199
no change for https://subversion.assembla.com/svn/x/trunk/Aplication/folder/src/com/ws/ios/services since the previous build
Checking console output
/var/lib/jenkins/jobs/folder/builds/26/log:
Building in workspace /var/lib/jenkins/jobs/folder/workspace
Will not revert since build status is not UNSTABLE.
Finished: SUCCESS 
this is the first build.  this build is (Blue) and i only testing one folder (services).

now im going to push something new in my folder (services). 
i will delete in my folder services some files.

Started by remote host 64.250.188.35
Building in workspace /var/lib/jenkins/jobs/folder/workspace
Updating https://subversion.assembla.com/svn/x/trunk/Aplication/folder/src/com/ws/ios/services at revision '2015-02-25T09:54:44.985 -0500'
D         UsuarioService - Copy - Copy (6).java
D         UsuarioService - Copy - Copy (8).java
D         UsuarioService - Copy - Copy (9).java
D         UsuarioService - Copy - Copy (3) - Copy.java
D         UsuarioService - Copy - Copy (4) - Copy.java
D         UsuarioService - Copy - Copy (5) - Copy.java
D         UsuarioService - Copy - Copy (6) - Copy.java
D         UsuarioService - Copy - Copy (7) - Copy.java
D         UsuarioService - Copy - Copy (8) - Copy.java
D         UsuarioService - Copy - Copy (9) - Copy.java
D         UsuarioService - Copy.java
D         UsuarioService - Copy - Copy (10) - Copy.java
D         UsuarioService - Copy - Copy.java
D         UsuarioService - Copy - Copy (2).java
D         UsuarioService - Copy - Copy (3).java
D         UsuarioService - Copy - Copy (5).java
At revision 201
Checking console output
/var/lib/jenkins/jobs/folder/builds/28/log:
Building in workspace /var/lib/jenkins/jobs/folder/workspace
Build step 'Jenkins Text Finder' changed build result to UNSTABLE
Will not revert since some changes in commit(s) outside workspace detected.
Finished: UNSTABLE

and my workspace is the folder services
the previous build is stable (blue) 
the previous build is completed . (one build is completed when a build it was started and finished with any result, including failed builds. ).
the current build is unstable . (yellow)
the current build contains changes – a new commit not in the previous build.
my workspace have some  changes in the commit. im following the rules i think.
any idea?

**Comment by davidparsson** [comment]
I'm assuming the commit only contains files deleted from that folder, and nothing else?

Have you configured a custom workspace folder?

What are the versions of your Jenkins, SVN, SVN plugin and svn-revert-plugin?

**Comment by oOBlinkOo** [comment]
No the folder have more files.
The output only show the files where have changes. (add, delete,update). This isn't the first build.

I dont config a custom workspace folder. My workspace in this case is:

![jenkins1buena](https://cloud.githubusercontent.com/assets/5222538/6398808/d94d5ad6-bdb3-11e4-8069-153d7862792a.png)

my workspace target the folder in svn services (servicios) this is svn:
![jenkins2](https://cloud.githubusercontent.com/assets/5222538/6398933/ce0e850e-bdb4-11e4-95b4-cd46fee6e147.png)

 in the jenkins target folder services: 
![jenkins3](https://cloud.githubusercontent.com/assets/5222538/6398983/33600a9a-bdb5-11e4-9a7c-b94f1fd7ddae.png)

my jenkins v 1.599 
subersion plugin v 2.4
subversion revert plugin v 1.3
im using svn on assembla v 1.80

**Comment by davidparsson** [comment]
Frankly, I have no idea on what's wrong. I've not tried this plugin on recent versions of Jenkins, so that may possibly be the cause.

The source code is available here on GitHub, so if you're up for it you're welcome to continue investigations on your own.

**Comment by oOBlinkOo** [comment]
hey... finally i could!!! hahaha the last week. i delete some files in the folder of plugins files with .jpi and i get it. the plugin work at version 2.4 but the newest version 2.5 in svn plugin delete some functions!! now if you want to use you have to use svn plugin v 2.4 hahahah
